version: '3.5'
services:
    server:
        build: .
        container_name: dao-signaling-server
        ports:
            - '8083:8083'
        networks:
            - docker-net
        # TODO : 볼륨 지정
networks:
    docker-net:
