version: '3.5'
services:
    server:
        build: .
        environment:
            - PORT=8083
            - MAXIMUM=4
        ports:
            - '8083:8083'
        networks:
            - docker-net
networks:
    docker-net:
